version: '2'

services:

  java-agent:
    container_name: java-agent
    hostname: java-agent
    image: appdynamics/java-agent:latest
    volumes:
      - java-agent:/opt/appdynamics  

  mongo-sessions:
    image: mongo
    container_name: mongo-sessions
    hostname: mongo-sessions
    expose: 
      - 27017

  mongo-accounts:
    image: mongo
    container_name: mongo-accounts
    hostname: mongo-accounts
    expose: 
      - 27017

  web-api:
    image: brownkw/appd_lambda_lab_java_services:v1
    hostname: web-api
    container_name: web-api
    volumes:
      - './graph.json:/graph.json'
      - java-agent:/opt/appdynamics/java-agent/
    env_file: controller.env
    environment: 
      - GRAPH_FILE=/graph.json
      - JAVA_TOOL_OPTIONS=-javaagent:/opt/appdynamics/java-agent/javaagent.jar
      - DEBUG_LEVEL=debug      
      - APPDYNAMICS_AGENT_TIER_NAME=web-api-${LAB_SUFFIX}
      - APPDYNAMICS_AGENT_NODE_NAME=web-api-${LAB_SUFFIX}-1
      - APPDYNAMICS_AGENT_ACCOUNT_NAME=${APPDYNAMICS_AGENT_ACCOUNT_NAME}
      - APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY=${APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY}
    ports:
      - '8080:8080'

  auth-services:
    image: brownkw/appd_lambda_lab_nodejs_services:v1
    hostname: auth-services
    container_name: auth-services
    volumes:
      - './graph.json:/graph.json'
    env_file: controller.env
    environment: 
      - GRAPH_FILE=/graph.json
      - DEBUG_LEVEL=debug      
      - APPDYNAMICS_AGENT_TIER_NAME=auth-services-${LAB_SUFFIX}
      - APPDYNAMICS_AGENT_NODE_NAME=auth-services-${LAB_SUFFIX}-1
      - APPDYNAMICS_AGENT_ACCOUNT_NAME=${APPDYNAMICS_AGENT_ACCOUNT_NAME}
      - APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY=${APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY}
    expose:
      - 3000

  data-services:
    image: brownkw/appd_lambda_lab_nodejs_services:v1
    hostname: data-services
    container_name: data-services
    volumes:
      - './graph.json:/graph.json'
    env_file: controller.env
    environment: 
      - GRAPH_FILE=/graph.json
      - DEBUG_LEVEL=debug      
      - APPDYNAMICS_AGENT_TIER_NAME=data-services-${LAB_SUFFIX}
      - APPDYNAMICS_AGENT_NODE_NAME=data-services-${LAB_SUFFIX}-1
      - APPDYNAMICS_AGENT_ACCOUNT_NAME=${APPDYNAMICS_AGENT_ACCOUNT_NAME}
      - APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY=${APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY}
    expose:
      - 3000      

  core-services:
    image: brownkw/appd_lambda_lab_java_services:v1
    hostname: core-services
    container_name: core-services
    volumes:
      - './graph.json:/graph.json'
      - java-agent:/opt/appdynamics/java-agent/
    env_file: controller.env
    environment: 
      - GRAPH_FILE=/graph.json
      - JAVA_TOOL_OPTIONS=-javaagent:/opt/appdynamics/java-agent/javaagent.jar
      - APPDYNAMICS_AGENT_TIER_NAME=core-services-${LAB_SUFFIX}
      - APPDYNAMICS_AGENT_NODE_NAME=core-services-${LAB_SUFFIX}-1
      - APPDYNAMICS_AGENT_ACCOUNT_NAME=${APPDYNAMICS_AGENT_ACCOUNT_NAME}  
      - APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY=${APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY}
    expose:
      - 8080

  job-listing-services:
    image: brownkw/appd_lambda_lab_java_services:v1
    hostname: job-listing-services
    container_name: job-listing-services
    volumes:
      - './graph.json:/graph.json'
      - java-agent:/opt/appdynamics/java-agent/
    env_file: controller.env
    environment: 
      - GRAPH_FILE=/graph.json
      - JAVA_TOOL_OPTIONS=-javaagent:/opt/appdynamics/java-agent/javaagent.jar
      - APPDYNAMICS_AGENT_TIER_NAME=job-listing-services-${LAB_SUFFIX}
      - APPDYNAMICS_AGENT_NODE_NAME=job-listing-services-${LAB_SUFFIX}-1
      - APPDYNAMICS_AGENT_ACCOUNT_NAME=${APPDYNAMICS_AGENT_ACCOUNT_NAME}  
      - APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY=${APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY}
    expose:
      - 8080      

  candidate-services:
    image: brownkw/appd_lambda_lab_java_services:v1
    hostname: candidate-services
    container_name: candidate-services
    volumes:
      - './graph.json:/graph.json'
      - java-agent:/opt/appdynamics/java-agent/
    env_file: controller.env
    environment: 
      - GRAPH_FILE=/graph.json
      - JAVA_TOOL_OPTIONS=-javaagent:/opt/appdynamics/java-agent/javaagent.jar
      - APPDYNAMICS_AGENT_TIER_NAME=candidate-services-${LAB_SUFFIX}
      - APPDYNAMICS_AGENT_NODE_NAME=candidate-services-${LAB_SUFFIX}-1
      - APPDYNAMICS_AGENT_ACCOUNT_NAME=${APPDYNAMICS_AGENT_ACCOUNT_NAME}  
      - APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY=${APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY}
    expose:
      - 8080        

volumes:
  java-agent: